### ISSUE TITLE
Licenca

### ISSUE THREAD

**Issue by ejmastnak** [mihapompe/FMF-Fizika-zapiski#1]
Hojla! Super, da si objavil zapiske. 

Zelel sem sporocit iz lastnih izkusenj: za objavo knjig/zapiskov/slik je baje bolje izbrati katero od Creative Commons licenc, kot software-sko licenco kot je MIT. Mene so nekateri profesorji na to opozarjali ko sem objavil svoje zapiske; verjetno je tudi tukaj relevantno. Seveda ti s tem ne zelim tezit, in bos na koncu ti presodil, kaj je najbolje. 

Ce se odlocis za CC licenso, lahko najdes Markdown verzije vseh razlicic v [1] in TDLR razlage v [2]. CC-BY licenca [3] je najbolj podobna MIT-ju. Meni (in profesorjem) je malo bolj vsec CC-BY-NC-SA [4], ker zahteva, da so derivati tvojega dela tudi open source and brezplacno dostopni. Ampak to itak ni "high stakes" situacija in v praksi odlocitev v tem primeru verjetno ni tako bistvena. 

V vsakem primeru lepo, da si objavil zapiske!

- [1] https://github.com/idleberg/Creative-Commons-Markdown/tree/master/4.0
- [2] https://creativecommons.org/about/cclicenses/
- [3] https://creativecommons.org/licenses/by/4.0/deed.sl
- [4] https://creativecommons.org/licenses/by-nc-sa/4.0/deed.sl

**Comment by mihapompe** [comment]
Živjo, hvala za nasvet. Sem posodobil in je sedaj CC-BY-NC-SA.
